### ISSUE TITLE
Does not work with typescript

### ISSUE THREAD

**Issue by tonhao-dev** [meetzaveri/react-donut#13]
when trying to install library typing using:
`npm install @types/react-donut -D`

I get the following error message: 
`@types/react-donut@latest' is not in the npm registry.`

**Comment by meetzaveri** [comment]
@luis-antonio-ac  Thanks for reporting this issue. I'll look into this

**Comment by tonhao-dev** [comment]
Hello, good night, any news about this?

**Comment by meetzaveri** [comment]
@luis-antonio-ac  Haven't looked. Can you assist to solve this bug ? Much more appreciated!

**Comment by meetzaveri** [comment]
@luis-antonio-ac Hello. Thanks for pinching me 😄. 

Yeah, this morning I worked on this and have added type definitions to this package. New package version is available on npm with version - **1.1.4**

Again, thanks for your feedback !

link - https://www.npmjs.com/package/react-donut

**Comment by meetzaveri** [comment]
I think that `@types` error will persist, but your use-case of having type definitions for package's API is being solved by latest update. Let me know if you have still any problem
